# Generated by Django 3.2.7 on 2022-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.TextField(default='GOOOOOOOOOOOOOOOOOOOLE is best'),
        ),
    ]
